calibration:
  apgaintable: /Data/omkar/HI_DATA/quenched_hi/AGC203001/scan1/out_AGC203001/apgain.cal
  bpassgaintable: /Data/omkar/HI_DATA/quenched_hi/AGC203001/scan1/out_AGC203001/bpassgain.gcal
  bpasstable: /Data/omkar/HI_DATA/quenched_hi/AGC203001/scan1/out_AGC203001/bandpass.cal
  ch0_spw: 0:250~300
  delaytable: /Data/omkar/HI_DATA/quenched_hi/AGC203001/scan1/out_AGC203001/delays.cal
  fluxscaletable: /Data/omkar/HI_DATA/quenched_hi/AGC203001/scan1/out_AGC203001/fluxscale.tbl
  gaintables:
  - /Data/omkar/HI_DATA/quenched_hi/AGC203001/scan1/out_AGC203001/delays.cal
  - /Data/omkar/HI_DATA/quenched_hi/AGC203001/scan1/out_AGC203001/bandpass.cal
  - /Data/omkar/HI_DATA/quenched_hi/AGC203001/scan1/out_AGC203001/fluxscale.tbl
  ini_nloops: 1
  nloops: 5
cube:
  deconvolver: hogbom
  robust: 0.5
  vel_res: 14
  weighting: briggs
flagging:
  badants:
  - W06
  beta:
  - 0.7
  - 0.7
  - 0.7
  fcut_list:
  - 6
  - 6
  - 6
  flagcmd: false
  refant: C00
  spw: 0:0~20;460~511
  tcut_list:
  - 6
  - 6
  - 6
  uplims_list:
  - 20
  - 20
  - 20
general:
  bandcal: null
  fitsfile: null
  fluxcal:
  - 3C286
  - 3C147
  fluxscale_list:
  - 15
  - 22.5
  - 1.3401288773440032
  - 1.340641479445702
  - 1.3408088943677705
  - 1.3405736385864535
  msfile: /Data/omkar/HI_DATA/quenched_hi/AGC203001/scan2/AGC203001.ms #Not required
  outdir: /Data/omkar/HI_DATA/quenched_hi/AGC203001/scan2/out_AGC203001/
  phasecal: 1111+199
  spw: '0'
  target: AGC203001
  targetcalfile: /Data/omkar/HI_DATA/quenched_hi/AGC203001/scan2/AGC203001_scan2.ms
  temp: /Data/omkar/HI_DATA/quenched_hi/AGC203001/scan2/temp/
  uvran: 0~100klambda
  yarp_version: v0.9.0
imagecal:
  aploops: 1
  cell: 0.4
  chanbin: 29
  imsize: 4500
  niter_range_p:
  - 2000
  - 5000
  nloops: 2
  nterms: 1
  outimage: AGC203001_cont
  ploops: 5
  regionfile: /Data/omkar/HI_DATA/quenched_hi/AGC203001/scan2/out_AGC203001/regions/AGC203001_stats_region.crtf
  robust: 0
  scales:
  - 0
  - 5
  - 10
  solints_p:
  - 8
  - 1
  solints_ap:
  - 15
  - 15
  spec_line_spw: '*:1393.37~1395.37MHz'
  threshold_final: 0.04
  threshold_range_p:
  - 1
  - 0.06
  threshold_range_ap: 
  - 0.06
  - 0.06
  uvran: 0.5~100klambda
  uvtaper:
  - 90klambda
  weighting: briggs
  wprojplanes: -1
uvsub:
  fitorder: 1
  linefreespw: '0:50~200;300~450'
  linespw: '0:201~299'
