calibration:
  apgaintable: /Data/omkar/HI_DATA/quenched_hi/AGC723834/out_AGC723834/apgain.cal
  bpassgaintable: /Data/omkar/HI_DATA/quenched_hi/AGC723834/out_AGC723834/bpassgain.gcal
  bpasstable: /Data/omkar/HI_DATA/quenched_hi/AGC723834/out_AGC723834/bandpass.cal
  ch0_spw: 0:250~300
  delaytable: /Data/omkar/HI_DATA/quenched_hi/AGC723834/out_AGC723834/delays.cal
  fluxscaletable: /Data/omkar/HI_DATA/quenched_hi/AGC723834/out_AGC723834/fluxscale.tbl
  gaintables:
  - /Data/omkar/HI_DATA/quenched_hi/AGC723834/out_AGC723834/delays.cal
  - /Data/omkar/HI_DATA/quenched_hi/AGC723834/out_AGC723834/bandpass.cal
  - /Data/omkar/HI_DATA/quenched_hi/AGC723834/out_AGC723834/fluxscale.tbl
  ini_nloops: 1
  nloops: 1
cube:
  deconvolver: hogbom
  robust: 0.5
  vel_res: 7
  weighting: briggs
flagging:
  badants:
  - E04
  - E05
  - E06
  beta:
  - 0.7
  - 0.7
  - 0.7
  fcut_list:
  - 6
  - 6
  - 6
  flagcmd: /Data/omkar/HI_DATA/quenched_hi/AGC723834/out_AGC723834/flag.txt
  refant: C00
  spw: false
  tcut_list:
  - 6
  - 6
  - 6
  uplims_list:
  - 20
  - 20
  - 20
general:
  bandcal: null
  fitsfile: null
  fluxcal:
  - 3C286
  fluxscale_list:
  - 15
  msfile: /Data/omkar/HI_DATA/quenched_hi/AGC723834/AGC723834_cen1K.ms
  outdir: /Data/omkar/HI_DATA/quenched_hi/AGC723834/out_AGC723834/
  phasecal: 1125+261
  spw: '0'
  target: AGC723834
  targetcalfile: /Data/omkar/HI_DATA/quenched_hi/AGC723834/AGC723834_yarp_cal.ms
  temp: /Data/omkar/HI_DATA/quenched_hi/AGC723834/temp/
  uvran: 0~100klambda
  yarp_version: v0.9.0
imagecal:
  aploops: 1
  cell: 0.4
  chanbin: 82
  imsize: 4500
  niter_range:
  - 2000
  - 5000
  nloops: 2
  nterms: 1
  outimage: AGC723834_cont
  ploops: 3
  regionfile: /Data/omkar/HI_DATA/quenched_hi/AGC723834/out_AGC723834/regions/stats_region.crtf
  robust: 0
  scales:
  - 0
  - 5
  - 15
  solints:
  - 8
  - 1
  spec_line_spw: 0:5~6
  threshold_final: 0.05
  threshold_range:
  - 1
  - 0.06
  uvran: 0.5~100klambda
  uvtaper:
  - 90klambda
  weighting: briggs
  wprojplanes: -1
uvsub:
  fitorder: 1
  linefreespw: 0:10~350;450~800
  linespw: 0:351~449
