calibration:
  apgaintable: apgain.cal
  bpassgaintable: bpassgain.gcal
  bpasstable: bandpass.cal
  delaytable: delays.cal
  fluxscaletable: fluxscale.tbl
  gaintables:
  - delays.cal
  - bandpass.cal
  - fluxscale.tbl
cube:
  deconvolver: hogbom
  robust: 0.5
  vel_res: 14
  weighting: briggs
flagging:
  badants:
  - E03
  - E04
  - E05
  - E06
  - W06
  - W03
  refant: C00
  spw: False
generalA:
  bandcal: null
  fitsfile: null
  fluxcal:
  - 3C286
  - 3C147
  fluxscale_list: [15, 22.5]
  uplims_list: [20, 20, 20]
  beta: [0.7, 0.7, 0.7]
  tcut_list: [6, 6, 6]
  fcut_list: [6, 6, 6]
  msfile: /Data/omkar/HI_DATA/quenched_hi/AGC722572_cen2K.ms
  outdir: /Data/omkar/HI_DATA/quenched_hi/out_AGC722572/
  phasecal: 1125+261
  spw: '0'
  target: AGC722572
  targetcalfile: /Data/omkar/HI_DATA/quenched_hi/AGC722572_yarp_cal.ms
  temp: /temp1/omkar/temp/
  uvran: 0~100klambda
  yarrp_version: v0.9.0
imagecal:
  aploops: 1
  cell: 0.4
  chanbin: 82
  imsize: 4500
  niter_range:
  - 2000
  - 5000
  nloops: 1
  nterms: 2
  outimage: AGC722572_cont
  ploops: 4
  regionfile: /Data/omkar/HI_DATA/quenched_hi/out_AGC722572/regions/stats_region.crtf
  robust: 0
  scales:
  - 0
  - 5
  - 15
  solints:
  - 8
  - 1
  spec_line_spw: 0:5~6
  threshold_final: 0.03
  threshold_range:
  - 1
  - 0.06
  uvran: 0.5~100klambda
  uvtaper:
  - 90klambda
  weighting: briggs
  wprojplanes: -1
uvsub:
  fitorder: 1
  linefreespw: 0:10~428;596~1014
  linespw: 0:429~595
